# Generated by Django 3.2.23 on 2023-12-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('phonenumber', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('is_active', models.IntegerField(default=1)),
            ],
        ),
    ]
