# Generated by Django 3.2.23 on 2023-12-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QUIZAPP', '0002_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('maths', 'Maths'), ('english', 'English'), ('gk', 'General Knowledge')], default=None, max_length=255, null=True),
        ),
    ]
